import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

describe('anonymous specialist chat UI acceptance', () => {
  it('exposes specialist selection, AI notice, citation area, and a visible pending-question queue', async () => {
    const page = await readFile('pages/index.vue', 'utf8')
    const drawer = await readFile('components/AppDrawer.vue', 'utf8')
    const authModal = await readFile('components/AuthModal.vue', 'utf8')
    const css = await readFile('assets/css/main.css', 'utf8')
    const shellSources = `${page}\n${drawer}\n${authModal}`

    expect(page).toContain('/api/specialists')
    expect(page).toContain('/api/chat')
    expect(page).toContain('Conteúdo gerado por IA. Pode conter erros. Confirme sempre a resposta nas fontes citadas. As respostas não substituem aconselhamento profissional.')
    expect(page).toContain('Ainda não há especialidades disponíveis. Volte mais tarde.')
    expect(page).toContain('Fila de perguntas')
    expect(page).toContain('queueLimit = 3')
    expect(page).toContain('Subir')
    expect(page).toContain('Descer')
    expect(page).toContain('Remover')
    expect(page).toContain('Fontes')
    expect(page).toContain('quotaError')
    expect(page).toContain('Atingiu o limite de perguntas gratuitas. Crie uma conta para continuar.')
    expect(page).toContain('A consultar as fontes desta especialidade…')
    expect(page).toContain('slowResponseNoticeDelayMs = 30_000')
    expect(page).toContain('Cancelar resposta')
    expect(page).toContain('AbortController')
    expect(shellSources).toContain('/api/auth/otp/request')
    expect(shellSources).toContain('/api/auth/otp/verify')
    expect(page).toContain('/api/auth/session')
    expect(page).toContain('/api/auth/logout')
    expect(page).toContain('/api/admin/session')
    expect(shellSources).toContain('Administração')
    expect(page).toContain('/api/history?specialistId=')
    expect(page).toContain('/api/history/')
    expect(page).toContain('Histórico')
    expect(page).toContain('Retomar')
    expect(page).toContain('Apagar')
    expect(page).toContain('Editar')
    expect(page).toContain('conversationId')
    expect(page).toContain('replaceFromMessageId')
    expect(shellSources).toContain('Entrar')
    expect(shellSources).toContain('Telemóvel')
    expect(shellSources).toContain('Terminar sessão')
    expect(page).toContain(':disabled="!canSubmitQuestion"')
    expect(css).toContain('.prompt--off { opacity: 0.55; }')
    expect(css).not.toContain('.prompt--off { opacity: 0.55; pointer-events: none; }')
  })
})
