import { mkdir, mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it, vi } from 'vitest'
import type { SpecialistRuntime } from '../server/utils/specialists/schema'

const createUjimuPiSessionMock = vi.hoisted(() => vi.fn())

vi.mock('../server/utils/pi/session', () => ({
  createUjimuPiSession: createUjimuPiSessionMock
}))

describe('specialist initialization prompt acceptance', () => {
  it('sends the initialization prompt with required files and chat protocol', async () => {
    const prompts: string[] = []
    createUjimuPiSessionMock.mockResolvedValue({
      session: {
        prompt: vi.fn(async (prompt: string) => {
          prompts.push(prompt)
        }),
        abort: vi.fn(async () => undefined),
        dispose: vi.fn()
      },
      agentLog: { close: vi.fn(async () => undefined) }
    })

    const { createPiSdkSpecialistInitializationRunner } = await import('../server/utils/specialists/initialization')
    const specialist = specialistRuntimeFixture()

    await createPiSdkSpecialistInitializationRunner().initializeSpecialist(specialist)

    const sessionOptions = createUjimuPiSessionMock.mock.calls[0][0]
    expect(sessionOptions).toMatchObject({ cwd: specialist.paths.root, task: 'initialization' })
    expect(sessionOptions).not.toHaveProperty('fileSystemPolicy')
    expect(sessionOptions).not.toHaveProperty('tools')
    expect(sessionOptions).not.toHaveProperty('appendSystemPromptOverride')
    expect(prompts[0]).toBe(`Use the \`llm-wiki\` skill to initialize this specialist workspace with the \`legislation-regulatory\` preset. The administrator has already approved the configuration below, so do not run an interactive domain interview. Use \`AGENTS.md\` as the schema file generated by \`llm-wiki\` and incorporate the Ujimu consultation rules below into that same file.

Specialist:
- id: perito-fintech
- name: Perito Fintech
- description: Especialista em regulação fintech angolana.
- wiki type: legislation-regulatory

The backend has already created raw/, converted/, wiki/, and ingest/. Respect the llm-wiki contract raw/ -> converted/ -> wiki/.

Create these required files:
- AGENTS.md
- wiki/index.md
- wiki/log.md

Do not invent source facts or legal content. The generated AGENTS.md must state that this workspace is governed by the \`llm-wiki\` skill and its OKF-backed raw/ -> converted/ -> wiki contract.

Ujimu consultation rules for AGENTS.md:
These rules apply only when answering user consultation questions, not during wiki initialization or source ingestion.

1. Assume this specialist persona:
   You are a Ujimu specialist consultation assistant. Answer as a careful domain specialist, using only this specialist wiki as your source of truth. If the wiki does not contain enough evidence, say that the current context is insufficient instead of guessing.
2. Treat this specialist wiki as the only source of truth. Do not answer from general model knowledge.
3. If the wiki lacks sufficient evidence, state that the current context is insufficient and do not guess.
4. Ground every substantive answer in the wiki and cite the original document title and relevant articles.
5. Do not expose physical or internal file paths to the user. \`sourceFile\` is internal machine-readable citation metadata and must not be repeated in answer text.
6. Before emitting the final consultation answer, read and apply the \`unslop\` skill. This style pass must not change grounded facts, legal meaning, citations, or the required output structure.
7. Machine-readable citations remain optional. When useful citations are available, they may be emitted as JSON lines in this shape:
   {"type":"citations","citations":[{"sourceTitle":"...","sourceFile":"raw/...","articleRefs":["Artigo ..."]}]}
8. Plain-text answers are acceptable. Missing or malformed citations are ignored by Ujimu instead of blocking the answer.
`)
  })

  it('rejects an initialized workspace that omits any required Ujimu consultation rule', async () => {
    const root = await mkdtemp(join(tmpdir(), 'ujimu-agents-validation-'))
    const wiki = join(root, 'wiki')
    await mkdir(wiki, { recursive: true })
    await writeFile(join(wiki, 'index.md'), '# Index\n')
    await writeFile(join(wiki, 'log.md'), '# Log\n')
    const specialist = {
      ...specialistRuntimeFixture(),
      paths: {
        ...specialistRuntimeFixture().paths,
        root,
        wiki
      }
    }
    const { assertSpecialistInitializedWorkspace } = await import('../server/utils/specialists/initialization')
    const requiredRules = [
      'governed by the `llm-wiki` skill',
      'only source of truth',
      'lacks sufficient evidence',
      'cite the original document title and relevant articles',
      'Do not expose physical or internal file paths to the user',
      'read and apply the `unslop` skill'
    ]
    const completeAgents = `# Specialist context\n\n${requiredRules.join('\n')}\n`

    for (const omittedRule of requiredRules) {
      await writeFile(join(root, 'AGENTS.md'), completeAgents.replace(`${omittedRule}\n`, ''))
      await expect(assertSpecialistInitializedWorkspace(specialist), omittedRule).rejects.toMatchObject({
        code: 'WIKI_INITIALIZATION_OUTPUT_MISSING'
      })
    }

    await writeFile(join(root, 'AGENTS.md'), completeAgents)
    await expect(assertSpecialistInitializedWorkspace(specialist)).resolves.toBeUndefined()
  })

  it('writes the specialist system prompt as a one-time initialization persona before the chat protocol', async () => {
    const prompts: string[] = []
    createUjimuPiSessionMock.mockResolvedValue({
      session: {
        prompt: vi.fn(async (prompt: string) => {
          prompts.push(prompt)
        }),
        abort: vi.fn(async () => undefined),
        dispose: vi.fn()
      },
      agentLog: { close: vi.fn(async () => undefined) }
    })

    const { createPiSdkSpecialistInitializationRunner } = await import('../server/utils/specialists/initialization')
    const specialist = specialistRuntimeFixture('Responder como consultor fiscal angolano.')

    await createPiSdkSpecialistInitializationRunner().initializeSpecialist(specialist)

    expect(prompts[0]).toContain(`---
Assume the following persona:
Responder como consultor fiscal angolano.
---

Chat response guidance:`)
  })
})

function specialistRuntimeFixture(systemPrompt = ''): SpecialistRuntime {
  return {
    id: 'perito-fintech',
    name: 'Perito Fintech',
    description: 'Especialista em regulação fintech angolana.',
    wiki_type: 'legislation-regulatory',
    system_prompt: systemPrompt,
    citations_required: true,
    streaming_enabled: true,
    status: 'initializing',
    company_id: null,
    paths: {
      root: '/tmp/ujimu/specialties/perito-fintech',
      config: '/tmp/ujimu/specialties/perito-fintech/specialist.yaml',
      raw: '/tmp/ujimu/specialties/perito-fintech/raw',
      converted: '/tmp/ujimu/specialties/perito-fintech/converted',
      wiki: '/tmp/ujimu/specialties/perito-fintech/wiki',
      ingest: '/tmp/ujimu/specialties/perito-fintech/ingest',
      ingestState: '/tmp/ujimu/specialties/perito-fintech/ingest/state.json'
    }
  }
}
