import { readFile, stat } from 'node:fs/promises'
import type { AgentSessionLogCloseStatus } from '../agents/logs'
import { createUjimuPiSession } from '../pi/session'
import type { SpecialistRuntime } from './schema'

export interface SpecialistInitializationRunner {
  initializeSpecialist(
    specialist: SpecialistRuntime,
    options?: SpecialistInitializationRunnerOptions
  ): Promise<void>
}

export interface SpecialistInitializationRunnerOptions {}

export class SpecialistInitializationError extends Error {
  constructor(
    public readonly code: 'PI_EXECUTION_FAILED' | 'WIKI_INITIALIZATION_OUTPUT_MISSING',
    message: string
  ) {
    super(message)
    this.name = 'SpecialistInitializationError'
  }
}

export function createPiSdkSpecialistInitializationRunner(): SpecialistInitializationRunner {
  return {
    async initializeSpecialist(specialist, options = {}) {
      await runPiSdkSpecialistInitialization(specialist, options)
    }
  }
}

export async function assertSpecialistInitializedWorkspace(specialist: SpecialistRuntime): Promise<void> {
  const requiredFiles = [
    specialist.paths.root + '/AGENTS.md',
    specialist.paths.wiki + '/index.md',
    specialist.paths.wiki + '/log.md'
  ]

  for (const file of requiredFiles) {
    const fileStat = await stat(file).catch(() => undefined)
    if (!fileStat?.isFile()) {
      throw new SpecialistInitializationError(
        'WIKI_INITIALIZATION_OUTPUT_MISSING',
        `Specialist initialization did not create required file ${file}.`
      )
    }
  }

  const agentsPath = specialist.paths.root + '/AGENTS.md'
  const agentsContent = await readFile(agentsPath, 'utf8')
  const requiredRules = [
    ['llm-wiki governance', /\bllm-wiki\b/iu],
    ['wiki-only grounding', /(?:only source of truth|sole (?:authoritative )?source|ground(?:ed|ing)?\s+(?:consultations?\s+)?exclusively\s+(?:in|on)\s+(?:this specialist\s+)?wiki)/iu],
    ['insufficient evidence handling', /lacks sufficient evidence/iu],
    ['original source citations', /cite the original document title and relevant articles/iu],
    ['internal path protection', /do not expose physical or internal file paths to the user/iu],
    ['unslop final pass', /read and apply the `?unslop`? skill/iu],
    ['derived write prohibition', /normal user consultations[^]*never create, edit, or delete `?wiki\/derived\/?`?[^]*explicit derivation job initiated by an administrator/iu]
  ] as const

  for (const [rule, pattern] of requiredRules) {
    if (!pattern.test(agentsContent)) {
      throw new SpecialistInitializationError(
        'WIKI_INITIALIZATION_OUTPUT_MISSING',
        `Specialist initialization did not include the required ${rule} instruction in ${agentsPath}.`
      )
    }
  }
}

async function runPiSdkSpecialistInitialization(
  specialist: SpecialistRuntime,
  _options: SpecialistInitializationRunnerOptions
): Promise<void> {
  const cwd = specialist.paths.root
  const { session, agentLog } = await createUjimuPiSession({
    cwd,
    task: 'initialization',
    modelEnvPrefix: 'UJIMU_PI_INITIALIZATION',
    agentLog: { specialistId: specialist.id }
  })
  let logStatus: AgentSessionLogCloseStatus = 'succeeded'

  try {
    await session.prompt(buildInitializationPrompt(specialist))
  } catch (error) {
    logStatus = 'failed'
    if (error instanceof SpecialistInitializationError) {
      throw error
    }

    throw new SpecialistInitializationError(
      'PI_EXECUTION_FAILED',
      error instanceof Error ? error.message : 'Pi specialist initialization failed.'
    )
  } finally {
    session.dispose()
    await agentLog?.close(logStatus)
  }
}

function buildInitializationPrompt(specialist: SpecialistRuntime): string {
  const persona = specialist.system_prompt.trim() || 'You are a Ujimu specialist consultation assistant. Answer as a careful domain specialist, using only this specialist wiki as your source of truth. If the wiki does not contain enough evidence, say that the current context is insufficient instead of guessing.'

  return `Use the \`llm-wiki\` skill to initialize this specialist workspace with the \`${specialist.wiki_type}\` preset. Treat this as initialization mode even though the backend has pre-created an empty \`wiki/\` directory. The administrator has already approved the configuration below, so do not run an interactive domain interview. Use \`AGENTS.md\` as the schema file generated by \`llm-wiki\` and incorporate the Ujimu consultation rules below into that same file.

Specialist:
- id: ${specialist.id}
- name: ${specialist.name}
- description: ${specialist.description}
- wiki type: ${specialist.wiki_type}

The backend has already created raw/, converted/, wiki/, and ingest/. Respect the llm-wiki contract raw/ -> converted/ -> wiki/.

Create these required files:
- AGENTS.md
- wiki/index.md
- wiki/log.md

Do not invent source facts or legal content. The generated AGENTS.md must state that this workspace is governed by the \`llm-wiki\` skill and its OKF-backed raw/ -> converted/ -> wiki contract.

Ujimu consultation rules for AGENTS.md:
These rules apply only when answering user consultation questions, not during wiki initialization or source ingestion.

1. Assume this specialist persona:
   ${persona}
2. Treat this specialist wiki as the only source of truth. Do not answer from general model knowledge.
3. If the wiki lacks sufficient evidence, state that the current context is insufficient and do not guess.
4. Ground every substantive answer in the wiki and cite the original document title and relevant articles.
5. Do not expose physical or internal file paths to the user. \`sourceFile\` is internal machine-readable citation metadata and must not be repeated in answer text.
6. Before emitting the final consultation answer, read and apply the \`unslop\` skill. This style pass must not change grounded facts, legal meaning, citations, or the required output structure.
7. During normal user consultations, never create, edit, or delete \`wiki/derived/\`. Only an explicit derivation job initiated by an administrator may create or update derived knowledge.
8. Machine-readable citations remain optional. When useful citations are available, they may be emitted as JSON lines in this shape:
   {"type":"citations","citations":[{"sourceTitle":"...","sourceFile":"raw/...","articleRefs":["Artigo ..."]}]}
9. Plain-text answers are acceptable. Missing or malformed citations are ignored by Ujimu instead of blocking the answer.
`
}
